### PR TITLE
Removed draft blog from index page

### PR DESCRIPTION
**Pull request by joncamfield**
Moved the sample blog to _drafts folder (show with --drafts when running jekyll) and moved the blog listing widget to the bottom of index page

### CODE REVIEW

**Comment by mfc** [comment]
I just came here to do the same thing! always one step ahead :P Probably worth you having merge rights since @Rafiot is a pretty busy person?

**Comment by Rafiot** [comment]
Woops, sorry for that. Merging!

**Comment by Rafiot** [comment]
Also, please tell me if you want to have admin rights on this repository, I don't see any reason I'm the only one allowed to merge :)

**Comment by seamustuohy** [comment]
Don't do it Rafiot! Day one of giving Jon admin access to the repo and BAM!

He's gonna start doing all sorts of joyous things

**Comment by Rafiot** [comment]
haha

**Comment by joncamfield** [comment]
I'll happily take merge powers; but can't promise I won't post cats.

**Pull request merged**
