### PR TITLE
improved the de translated version

### PR DESCRIPTION
**Pull request by deralexxx**
I removed a lot of stuff that was mostly copied by misstake using google translate, made it more readable, hope it helps.

https://github.com/RaReNet/DFAK/issues/48

### CODE REVIEW

**Comment by seamustuohy** [comment]
**An new contributor Appears!**

I don't have permissions to accept pull requests, but I wanted to say **thank you** for contributing you time to this project. It's great to see new contributors adding to the various existing projects in the space. I'll bother the admins to make sure they take a look.

**Comment by Rafiot** [comment]
Thank you very much! 

@seamustuohy I'll give you the rights :)

**Comment by mfc** [comment]
one note, I would not accept the metadata authorship change of the page. instead we should have a contributors page linking to who has contributed to github or something.

**Comment by Rafiot** [comment]
Good point, fixed :)

**Pull request merged**
